import { initializeApp, getApps, getApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getDataConnect } from 'firebase/data-connect';

// This file will be generated by the set_up_firebase tool
import firebaseConfig from '../../firebase-applet-config.json';

const app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApp();
export const auth = getAuth(app);

// Data Connect configuration
export const dataconnect = getDataConnect(app, {
  location: 'us-central1',
  connector: 'rpg-connector',
  service: 'rpg-nexus'
});

// If you are using the emulator
// connectDataConnectEmulator(dataconnect, 'localhost', 9399);
