# RPG Nexus Schema

type Profile @table(name: "profiles") {
  id: String! @primaryKey
  email: String! @unique
  displayName: String
  role: String @default(value: "Jogador")
  isAdmin: Boolean @default(value: false)
  createdAt: Timestamp @default(expr: "request.time")
}

type Instance @table(name: "instances") {
  id: UUID! @default(expr: "uuidV4()") @primaryKey
  name: String!
  description: String
  owner: Profile!
  status: String @default(value: "Ativa")
  maxPlayers: Int @default(value: 5)
  createdAt: Timestamp @default(expr: "request.time")
}
